version: '3.9'
services:
  app:
    container_name: test-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=reportDb
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: report_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=reportDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata: